### ISSUE TITLE
Add Remind for RH

### ISSUE THREAD

**Issue by AardWolf** [AardWolf/MHTimerBot#112]
Should be able to subscribe to relic hunter reminders. Bot would need to keep track of previous location and when bot sees something new, spams people who have requested that.

**Comment by AardWolf** [comment]
1. Expire relic hunter location at midnight UTC. This may need a new timer or we can add a check for the reset timer

2. Update the relic hunter location from either the webhook (updRH will have to check for expired location) or MHCT (only query the location if we don't see one set or the source is the webhook because it is sometimes unreliable)

3. Send out a reminder when either updates the location. If MHCT changes a webhook-source'd location send a second reminder with an OOPs.

**Comment by tehhowch** [comment]
We probably also should support specific location reminders, too, e.g.

```
remind rh <quantifiers> except <location nicknames>...
remind rh <quantifiers> <location nicknames>...
```
For example, maybe I only want to be notified when the Relic Hunter is in Moussu Picchu

**Comment by AardWolf** [comment]
Live in #143
