### ISSUE TITLE
Automatically read (& report) available time filters 

### ISSUE THREAD

**Issue by tehhowch** [AardWolf/MHTimerBot#113]
Right now one must first know the available time filters to use them with find/ifind.

We can hard code the current filters into the `help` output, but this requires updating every time a new one is added. Better would be to programmatically learn the ones that are available. We could either scrape @devjacksmith 's site to read the `<option>`  values, read from a local text file, etc.

I think the simplest is for Jack's server to have an endpoint that conveys this (and other?) information.

**Comment by DevJackSmith** [comment]
Agreed. I need to automated it on my end too, but i'll make a manual one for now.

**Comment by DevJackSmith** [comment]
@tehhowch @AardWolf done: https://mhhunthelper.agiletravels.com/time-filters.json

**Comment by DevJackSmith** [comment]
@tehhowch @AardWolf moved this to https://mhhunthelper.agiletravels.com/filters.php so it fetches it from db instead of hardcoded

**Comment by AardWolf** [comment]
Returns an array of these things:

`    {
        "code_name": "3_days",
        "display_name": "Last 3 Days",
        "start_time": null,
        "end_time": null,
        "updated": "1",
        "minimum_seen": "1",
        "sort": "2"
    },`

Notes - start_time not null and end_time is null means current event. That'd let "current" still be used but the link would have the right label.
Right now hlwn2018 has a start_time but no end_time. Default it to 3_days.

**Comment by AardWolf** [comment]
Should be fixed in PR 111
