### ISSUE TITLE
Add "whatsin" command for convertibles

### ISSUE THREAD

**Issue by AardWolf** [AardWolf/MHTimerBot#137]
Examples: `whatsin rare bristle woods`

Can use the loot nicknames used by ifind.

**Comment by fluentinstroll** [comment]
Hey! I'd like to take a crack at this, I presume when we use the `whatsin` command we want to get a list of possible contents?

Like the kind of list you get from agiletravels in the below picture?
![image](https://user-images.githubusercontent.com/32021785/101416703-63891c00-38b8-11eb-9899-a55d7ac39cb9.png)

**Comment by AardWolf** [comment]
Exactly. Similar to finding mice and loot, this would use the convertible microservice to produce a table of contents.

You'll need to also get the list of convertibles it knows, similar to mice and loot lists. Currently there are no nicknames for convertibles.

**Comment by AardWolf** [comment]
FYI - I'm not ignoring this, just hasn't been on my priority list while GWH data analysis was going on!

**Comment by AardWolf** [comment]
Implemented!
