### ISSUE TITLE
If someone queries RH location between reset and first refresh gets old location

### ISSUE THREAD

**Issue by AardWolf** [AardWolf/MHTimerBot#152]
If they search before the trigger updates the spreadsheet location based of dbgames and MHCT hasn't seen the new location yet we get the old location and since there was a reset we get a new notification.

We don't actually need to reset the RH location but can reset / clear the last_seen. The sheet should put a last_seen as well so we know when it was changed.

**Comment by tehhowch** [comment]
If the spreadsheet includes a UTC timestamp of when the location was set, it should be easy enough to prevent Larry from thinking it is a valid location

**Comment by AardWolf** [comment]
Since the sheet doesn't have a dev and prod difference I'll have to create a new one while testing a fix. Things could get gnarly for a bit!

**Comment by AardWolf** [comment]
Part of #161 fixes this and another bug it introduced
