### ISSUE TITLE
`whois` should allow searching by discord ID number

### ISSUE THREAD

**Issue by AardWolf** [AardWolf/MHTimerBot#163]
Needs a new keyword since other things that map to a number are assumed hunter IDs. Or it can set a limit for how high hunter ID is since discordIDs are snowflakes and very large numbers.

> All IDs are at least 17 digits

This was found on the Internet but seems trustworthy

**Comment by AardWolf** [comment]
Note - the good-first-issue only applies against the `whois.js` file / command restructuring; which is not released yet.

**Comment by tehhowch** [comment]
We can always search both, too

**Comment by AardWolf** [comment]
This command has been deprecated.
