### ISSUE TITLE
3_months filter never works, goes to 3_days filter

### ISSUE THREAD

**Issue by AardWolf** [AardWolf/MHTimerBot#215]
I tried with 3_mon, 3_months - both went to 3_days as the filter.

**Comment by AardWolf** [comment]
https://github.com/AardWolf/MHTimerBot/blob/7e4777366c8c21529c5c5e07f9f512f9194a90ca/src/modules/mhct-lookup.js#L228

It's as easy as removing this or changing it to look for 3_d and 3_m.

**Comment by fluentinstroll** [comment]
Hello! I'd love to take a look at this, can you assign it to me?

**Comment by AardWolf** [comment]
Done!
