### ISSUE TITLE
Response to next should include instructions for setting a reminder

### ISSUE THREAD

**Issue by AardWolf** [AardWolf/MHTimerBot#36]

**Comment by AardWolf** [comment]
Soft close, added but might not be pretty enough.

**Comment by AardWolf** [comment]
When timer doesn't have sub-area (reset) it shows undefined for how to set a reminder.

**Comment by AardWolf** [comment]
```
        var sched_syntax = "-mh remind " + youngTimer.getArea();
        if (typeof(youngTimer.getSubArea()) !== 'undefined') {
            sched_syntax += " " + youngTimer.getSubArea();
        }
            
        retStr = new Discord.RichEmbed()
//            .setTitle("next " + timerName) // removing this cleaned up the embed a lot
            .setDescription(youngTimer.getDemand() + "\n" + timeLeft(youngTimer.getNext()) +
                    "\nTo schedule this reminder: -mh remind " + sched_syntax) // Putting here makes it look nicer and fit in portrait mode
            .setTimestamp(new Date(youngTimer.getNext().valueOf()))
```

**Comment by AardWolf** [comment]
var sched_syntax = "-mh remind " + timerName.area;
        if (typeof(timerName.sub_area) !== 'undefined') {
            sched_syntax += " " + timerName.sub_area;
        }
            
        retStr = new Discord.RichEmbed()
//            .setTitle("next " + timerName) // removing this cleaned up the embed a lot
            .setDescription(youngTimer.getDemand() + "\n" + timeLeft(youngTimer.getNext()) +
                    "\nTo schedule this reminder: " + sched_syntax) // Putting here makes it look nicer and fit in portrait mode

**Comment by DevJackSmith** [comment]
fyi it's usually a bug or an enhancement... usually not both. Keep up good work :)

**Comment by AardWolf** [comment]
An enhancement that looked fine got bugged. I should have opened a bug though. Lazy!
